"""add_project_workspace

Revision ID: 276b2f20b5fb
Revises: g1h2i3scoped_pat
Create Date: 2026-06-04 14:02:41.353902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 — needed for AutoString references


# revision identifiers, used by Alembic.
revision: str = '276b2f20b5fb'
down_revision: Union[str, Sequence[str], None] = 'g1h2i3scoped_pat'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_workspaces',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('background_md', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('context_md', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_focus_md', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_workspaces_project_id'), 'project_workspaces', ['project_id'], unique=True)
    op.create_index(op.f('ix_project_workspaces_tenant_id'), 'project_workspaces', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_workspaces_tenant_id'), table_name='project_workspaces')
    op.drop_index(op.f('ix_project_workspaces_project_id'), table_name='project_workspaces')
    op.drop_table('project_workspaces')
    # ### end Alembic commands ###
