"""add_project_position

Revision ID: 2dfeffb4a94d
Revises: 318403ead6cb
Create Date: 2026-06-05 15:00:19.548395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 — needed for AutoString references


# revision identifiers, used by Alembic.
revision: str = '2dfeffb4a94d'
down_revision: Union[str, Sequence[str], None] = '318403ead6cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('position', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'position')
    # ### end Alembic commands ###
