"""add_saved_views_pages_cycles

Revision ID: 318403ead6cb
Revises: i1j2k3
Create Date: 2026-06-05 11:37:31.395360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 — needed for AutoString references
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '318403ead6cb'
down_revision: Union[str, Sequence[str], None] = 'i1j2k3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('end_date > start_date', name='ck_cycle_dates'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycles_project_id'), 'cycles', ['project_id'], unique=False)
    op.create_index(op.f('ix_cycles_tenant_id'), 'cycles', ['tenant_id'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('parent_page_id', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('content_md', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_parent_page_id'), 'pages', ['parent_page_id'], unique=False)
    op.create_index(op.f('ix_pages_project_id'), 'pages', ['project_id'], unique=False)
    op.create_index(op.f('ix_pages_tenant_id'), 'pages', ['tenant_id'], unique=False)
    op.create_table('saved_views',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("visibility != 'project' OR project_id IS NOT NULL", name='ck_shared_needs_project'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_views_owner_user_id'), 'saved_views', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_saved_views_project_id'), 'saved_views', ['project_id'], unique=False)
    op.create_index(op.f('ix_saved_views_tenant_id'), 'saved_views', ['tenant_id'], unique=False)
    op.create_table('cycle_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('cycle_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('added_by', sa.Uuid(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'task_id', name='uq_cycle_task')
    )
    op.create_index(op.f('ix_cycle_tasks_cycle_id'), 'cycle_tasks', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_cycle_tasks_task_id'), 'cycle_tasks', ['task_id'], unique=False)
    op.create_index(op.f('ix_cycle_tasks_tenant_id'), 'cycle_tasks', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_pat_tenant_id'), table_name='personal_access_tokens')
    op.drop_index(op.f('ix_pat_token_hash'), table_name='personal_access_tokens')
    op.drop_index(op.f('ix_pat_user_id'), table_name='personal_access_tokens')
    op.create_index(op.f('ix_personal_access_tokens_tenant_id'), 'personal_access_tokens', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_personal_access_tokens_token_hash'), 'personal_access_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_personal_access_tokens_user_id'), 'personal_access_tokens', ['user_id'], unique=False)
    op.alter_column('tasks', 'impl_hint',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'impl_hint',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_personal_access_tokens_user_id'), table_name='personal_access_tokens')
    op.drop_index(op.f('ix_personal_access_tokens_token_hash'), table_name='personal_access_tokens')
    op.drop_index(op.f('ix_personal_access_tokens_tenant_id'), table_name='personal_access_tokens')
    op.create_index(op.f('ix_pat_user_id'), 'personal_access_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_pat_token_hash'), 'personal_access_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_pat_tenant_id'), 'personal_access_tokens', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_cycle_tasks_tenant_id'), table_name='cycle_tasks')
    op.drop_index(op.f('ix_cycle_tasks_task_id'), table_name='cycle_tasks')
    op.drop_index(op.f('ix_cycle_tasks_cycle_id'), table_name='cycle_tasks')
    op.drop_table('cycle_tasks')
    op.drop_index(op.f('ix_saved_views_tenant_id'), table_name='saved_views')
    op.drop_index(op.f('ix_saved_views_project_id'), table_name='saved_views')
    op.drop_index(op.f('ix_saved_views_owner_user_id'), table_name='saved_views')
    op.drop_table('saved_views')
    op.drop_index(op.f('ix_pages_tenant_id'), table_name='pages')
    op.drop_index(op.f('ix_pages_project_id'), table_name='pages')
    op.drop_index(op.f('ix_pages_parent_page_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_cycles_tenant_id'), table_name='cycles')
    op.drop_index(op.f('ix_cycles_project_id'), table_name='cycles')
    op.drop_table('cycles')
    # ### end Alembic commands ###
