"""add_assistant_llm_model

Revision ID: 671f643554cc
Revises: 2dfeffb4a94d
Create Date: 2026-06-05 15:11:38.983618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 — needed for AutoString references


# revision identifiers, used by Alembic.
revision: str = '671f643554cc'
down_revision: Union[str, Sequence[str], None] = '2dfeffb4a94d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistant_workspaces', sa.Column('llm_model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistant_workspaces', 'llm_model')
    # ### end Alembic commands ###
