"""add_org_groups

Revision ID: 8b4871c3dd53
Revises: 671f643554cc
Create Date: 2026-06-08 16:35:12.752922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 — needed for AutoString references


# revision identifiers, used by Alembic.
revision: str = '8b4871c3dd53'
down_revision: Union[str, Sequence[str], None] = '671f643554cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_groups',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('parent_group_id', sa.Uuid(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_group_id'], ['org_groups.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'parent_group_id', 'name', name='uq_org_group_name')
    )
    op.create_index(op.f('ix_org_groups_parent_group_id'), 'org_groups', ['parent_group_id'], unique=False)
    op.create_index(op.f('ix_org_groups_tenant_id'), 'org_groups', ['tenant_id'], unique=False)
    op.create_table('org_group_members',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['org_groups.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'group_id', 'user_id', name='uq_org_group_member')
    )
    op.create_index(op.f('ix_org_group_members_group_id'), 'org_group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_org_group_members_tenant_id'), 'org_group_members', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_org_group_members_user_id'), 'org_group_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_group_members_user_id'), table_name='org_group_members')
    op.drop_index(op.f('ix_org_group_members_tenant_id'), table_name='org_group_members')
    op.drop_index(op.f('ix_org_group_members_group_id'), table_name='org_group_members')
    op.drop_table('org_group_members')
    op.drop_index(op.f('ix_org_groups_tenant_id'), table_name='org_groups')
    op.drop_index(op.f('ix_org_groups_parent_group_id'), table_name='org_groups')
    op.drop_table('org_groups')
    # ### end Alembic commands ###
